steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/beaming-key-350612/test-project:$SHORT_SHA',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/beaming-key-350612/test-project:$SHORT_SHA',
      ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'beta',
        'run',
        'deploy',
        'test-projec',
        '--image=gcr.io/beaming-key-350612/test-projec:$SHORT_SHA',
        '--region=us-central1',
      ]
